### ISSUE TITLE
can't get working :x

### ISSUE THREAD

**Issue by Owned67** [blueclouds8666/msupdate-dl#1]
`powershell -executionpolicy bypass -File .\MSUpdate-DL-Batch.ps1 -language="fra" -architecture="64" -output="F:\DISMTOOL\Updates"`

or
`.\MSUpdate-DL-Batch.ps1 -language="fra" -architecture="64" -output="F:\DISMTOOL\Updates"`

> [INFO] Update 1 of 16
> [INFO] Downloading KB898461                                                                                             
>[INFO] No language(s) > specified. Script will download English and Universal only                                        

> [INFO] Update 2 of 16

i can't have update for french langage so? il missunderstand something maybe?

Thanks

**Comment by blueclouds8666** [comment]
Sorry for the late response.

It seems that you used the incorrect format for execution arguments: since Release 1.02, all options use double slash instead of only one, but i forgot to change the examples at the readme and documentation, so that's entirely my fault. Your fixed command should now look like this:

`.\MSUpdate-DL-Batch.ps1 --language="fra" --architecture="64" --output="C:\msupdate-dl"`

I have just pushed a 1.03 update in order to fix the documentation, as well as a few other issues.

**Comment by Owned67** [comment]
no worries :)

how can i get the ntversion???

Ive try:
`./MSUpdate-DL-Batch.ps1 --language="fra" --architecture="64" --ntversion="100" --log` for windows 10 but it download XP...

**Comment by blueclouds8666** [comment]
This project is only intended for downloading updates released for the older windows versions, for that reason, filters for Windows 10 and 11 updates are not supported. You can try downloading updates without filters, but it is not guaranteed to work as expected.
